In [30]:
#import nessary model

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [31]:
#read csv file

df=pd.read_csv("laptopPrice.csv")
df.shape

(823, 19)

In [32]:
df.columns

Index(['brand', 'processor_brand', 'processor_name', 'processor_gnrtn',
       'ram_gb', 'ram_type', 'ssd', 'hdd', 'os', 'os_bit', 'graphic_card_gb',
       'weight', 'warranty', 'Touchscreen', 'msoffice', 'Price', 'rating',
       'Number of Ratings', 'Number of Reviews'],
      dtype='object')

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    object
 1   processor_brand    823 non-null    object
 2   processor_name     823 non-null    object
 3   processor_gnrtn    823 non-null    object
 4   ram_gb             823 non-null    object
 5   ram_type           823 non-null    object
 6   ssd                823 non-null    object
 7   hdd                823 non-null    object
 8   os                 823 non-null    object
 9   os_bit             823 non-null    object
 10  graphic_card_gb    823 non-null    object
 11  weight             823 non-null    object
 12  warranty           823 non-null    object
 13  Touchscreen        823 non-null    object
 14  msoffice           823 non-null    object
 15  Price              823 non-null    int64
 16  rating             823 non-null    object
 17  Number of Ratings  823 non-null    int64
 18  Number of Reviews  823 non-null    int64
dtypes: int64(3), object(16)
memory usage: 122.3+ KB

In [34]:
#check the isnull values to the dataset

df.isnull().sum()

brand                0
processor_brand      0
processor_name       0
processor_gnrtn      0
ram_gb               0
ram_type             0
ssd                  0
hdd                  0
os                   0
os_bit               0
graphic_card_gb      0
weight               0
warranty             0
Touchscreen          0
msoffice             0
Price                0
rating               0
Number of Ratings    0
Number of Reviews    0
dtype: int64

In [35]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [36]:
#split the "int" feature and "object" feature

objch=[]
numin=[]
for gh in df.columns:
    if df[gh].dtype=="object":
        objch.append(gh)
    else:
        numin.append(gh)

In [37]:
objch

['brand',
 'processor_brand',
 'processor_name',
 'processor_gnrtn',
 'ram_gb',
 'ram_type',
 'ssd',
 'hdd',
 'os',
 'os_bit',
 'graphic_card_gb',
 'weight',
 'warranty',
 'Touchscreen',
 'msoffice',
 'rating']

In [38]:
numin

['Price', 'Number of Ratings', 'Number of Reviews']

In [39]:
#check the unique values from the "object feature"

df[objch].nunique()

brand               8
processor_brand     3
processor_name     11
processor_gnrtn     8
ram_gb              4
ram_type            6
ssd                 7
hdd                 4
os                  3
os_bit              2
graphic_card_gb     5
weight              3
warranty            4
Touchscreen         2
msoffice            2
rating              5
dtype: int64

In [40]:
# split nominal charecters and ordinal charecters feature

targete=['brand','processor_brand','processor_name','processor_gnrtn','os','weight']
labele=['ram_gb','ram_type','ssd','hdd','os_bit','graphic_card_gb','warranty','Touchscreen','msoffice','rating']

In [41]:
#import encoders model

from sklearn.preprocessing import LabelEncoder
from category_encoders import TargetEncoder

In [42]:
# ordinal charecter feature values change to numerical values using "label encoder"
#(# nomial charecter feature values change to numerical value  using  "Target encoder"
# because this feature have lot of unique charecter)

for ta in targete:
    te=TargetEncoder()
    df[ta]=te.fit_transform(df[ta],df['Price'])
for la in labele:
    lab=LabelEncoder()
    df[la]=lab.fit_transform(df[ta])

In [43]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,78937.602409,73976.039344,42660.537291,89624.563594,2,2,2,2,73125.138639,2,2,85273.961538,2,2,2,34649,2,3,0
1,72920.224087,73976.039344,42660.537291,89624.563594,2,2,2,2,73125.138639,2,2,85273.961538,2,2,2,38999,2,65,5
2,72920.224087,73976.039344,42660.537291,89624.563594,2,2,2,2,73125.138639,2,2,85273.961538,2,2,2,39999,2,8,1
3,78937.602409,73976.039344,75326.403448,89624.563594,2,2,2,2,73125.138639,2,2,85273.961538,2,2,2,69990,2,0,0
4,78937.602409,73976.039344,45528.174493,68976.373343,2,2,2,2,73125.138639,2,2,85273.961538,2,2,2,26990,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,78937.602409,76614.481487,117592.260745,68976.373343,2,2,2,2,73125.138639,2,2,85273.961538,2,2,2,135990,2,0,0
819,78937.602409,76614.481487,117592.260745,68976.373343,2,2,2,2,73125.138639,2,2,85273.961538,2,2,2,144990,2,0,0
820,78937.602409,76614.481487,117592.260745,68976.373343,2,2,2,2,73125.138639,2,2,85273.961538,2,2,2,149990,2,0,0
821,78937.602409,76614.481487,117592.260745,68976.373343,2,2,2,2,73125.138639,2,2,85273.961538,2,2,2,142990,2,0,0
822,72920.224087,76614.481487,61311.054190,89624.563594,0,0,0,0,94830.698280,0,0,60319.973485,0,0,0,57490,0,18,4

In [58]:
# FIND THE CORRELATION BETWEEN TARGET TO INDEPENDENT FEATUREs

corre=abs(df.corr()['Price'])
corre

brand              0.362899
processor_brand    0.275238
processor_name     0.704687
ram_gb             0.255582
ram_type           0.255582
ssd                0.255582
hdd                0.255582
os                 0.341835
os_bit             0.255582
graphic_card_gb    0.255582
weight             0.255664
warranty           0.255582
Touchscreen        0.255582
msoffice           0.255582
Price              1.000000
rating             0.255582
Name: Price, dtype: float64

In [45]:
#filter the porr correlation feature to target feature

badcorr=corre[corre<0.25]
badcorr

processor_gnrtn      0.224714
Number of Ratings    0.140392
Number of Reviews    0.148738
Name: Price, dtype: float64

In [46]:
#drop the bad correlation features

df.drop(badcorr.index,axis=1,inplace=True)

In [47]:
df.shape

(823, 16)

In [48]:
X=df.drop('Price',axis=1)
y=df['Price']

In [49]:
#import regression model algorithums

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
# import evalation metrics
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
from sklearn.linear_model import Ridge
# import ensemble  stacking metod to use increase accureasy 
from sklearn.ensemble import StackingRegressor


X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [50]:
X_train.shape

(617, 15)

In [51]:
X_test.shape

(206, 15)

In [52]:
#train the model and predict the values then find the accuracy of mae,mse,r2_score

models=[LinearRegression(),DecisionTreeRegressor(),RandomForestRegressor(),SVR()]
for mo in models:
    mod=mo
    mod.fit(X_train,y_train)
    pre=mod.predict(X_test)
    mae=mean_absolute_error(pre,y_test)
    mse= mean_squared_error(pre,y_test)
    r2=r2_score(pre,y_test)
    print()
    print(mo)
    print("mean_absolute_error",mae)
    print()
    print("mean_squared_error",mse)
    print()
    print("r2_score",r2)
    print()

LinearRegression()
mean_absolute_error 19004.907917148877

mean_squared_error 956928907.1631795

r2_score 0.2164567789174946


DecisionTreeRegressor()
mean_absolute_error 17440.768191465082

mean_squared_error 905723636.166935

r2_score 0.6420109382906454


RandomForestRegressor()
mean_absolute_error 16444.201326886337

mean_squared_error 704838057.0289702

r2_score 0.6436089963347194


SVR()
mean_absolute_error 29821.896573625985

mean_squared_error 2190969387.0384135

r2_score -3621526.158735051

In [59]:
# RandomForestRegressor() and DecisionTreeRegressor() is a good traind model

In [57]:
# increase accurasy i using stackingregressor


# Define base models
base_models = [
    ('lr', LinearRegression()),
    ('rf', RandomForestRegressor(random_state=42)),
    ('svr', SVR()),
    ('dc',DecisionTreeRegressor())
]

# Initialize the StackingRegressor with the base models and a meta-model
stacked_model = StackingRegressor(estimators=base_models, final_estimator=Ridge())

# Fit the stacked model on the training data
stacked_model.fit(X_train, y_train)

# Evaluate the stacked model on the testing data
score = stacked_model.score(X_test, y_test)
print(f"Stacked model R^2 score: {score:.3f}")
print(f"staked model mean_squared_error: {score:}")
print(f"staked mean_absolute_error:{score:}")

Stacked model R^2 score: 0.663
staked model mean_squared_error: 0.6626924710040737
staked mean_absolute_error:0.6626924710040737

In [ ]:
# finaly i increase  the accuracy